site_name: Summary Igor Mamontov ver.1
site_url: https://Mamontosik.github.io/IgorMamontov_Summary
theme:
  name: 'material'
  icon:
    set: 'material'
  features:
    - navigation.path
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
nav:
  - Обо мне: 'index.md'